name: Group Welcome Bot Service

on:
  schedule:
    - cron: '*/15 * * * *' # هر ۱۵ دقیقه چک می‌کند ربات روشن باشد
  workflow_dispatch: # اجازه اجرای دستی

# جلوگیری از اجرای همزمان دو ربات (حل مشکل پیام تکراری)
concurrency:
  group: welcome-bot-group
  cancel-in-progress: true

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install telethon

      - name: Start Bot
        timeout-minutes: 350
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: python main.py
